Repository githubschool/green-giant, pull requests merged in 2021-11, with the labels that each got.

#10 Updates caption
  _slides/02-gusshawstewart.md
Labels: documentation, enhancement

#9 Update 11-RenatSeredzhinov.md
  _slides/11-RenatSeredzhinov.md
Labels: documentation, enhancement

#20 Updates caption
  _slides/04-KopIlya.md
Labels: documentation

#11 Updates caption
  _slides/03-Bright-Burn.md
Labels: documentation, enhancement

#12 Updates caption dv-ovodov
  _slides/08-dv-ovodov.md
Labels: enhancement

#16 updates caption
  _slides/15-BelalovBM.md
Labels: good first issue

#14 This PR changes very-anonymous's caption
  _slides/10-very-anonymous.md
Labels: documentation

#15 Update caption
  _slides/06-aruchibarudo.md
Labels: documentation, enhancement
